CREATE TABLE IF NOT EXISTS cheques (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	login VARCHAR(50),
	cashboxId INTEGER,
	change VARCHAR(50),
	chequeDate VARCHAR(50),
	chequeNumber VARCHAR(50),
	clientId INTEGER,
	clientAmount VARCHAR(50),
	clientComment VARCHAR(50),
	saleCurrencyId VARCHAR(50),
	currencyId VARCHAR(50),
	discount VARCHAR(50),
	itemsList TEXT,
	note VARCHAR(1000),
	ofdTransactions TEXT,
	offline BOOLEAN,
	outType BOOLEAN,
	paid VARCHAR(50),
	posId INTEGER,
	shiftId INTEGER,
	totalPrice VARCHAR(50),
	transactionId VARCHAR(100),
	transactionsList TEXT,
	systemId INTEGER,
	chequeId INTEGER,
	status INTEGER,
	cashboxVersion VARCHAR(50)
)